# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PxesCRWEYAfP6YkEseuCTlH0e0eGKScI
"""

def futbolchilar(belgi):
  if belgi== "Argentina":
    return "Messi"
  elif belgi == "Braziliya":
    return "Vini"
  elif belgi == "Daniya":
    return "Eriksen"
  elif belgi == "fransiya":
    return "Mbappe"
  elif belgi == "Portugaliya":
    return "Ronaldo"
  elif belgi == "Angliya":
    return "Bellingham"
  elif belgi == "Polsha":
    return "Levandowski"
  elif belgi == "Uzbekistan":
    return "Shomurodov"
  elif belgi == "Germaniya":
    return "Kroos"
  elif belgi == "Shvetsariya":
    return "Shaqiri"
  else:
    return "boshqa saytlardan qidirib koring"
belgi=input ("davlatni kiriting")
natija= futbolchilar(belgi)
print(natija)